name: Bug Report
description: File a bug report.
labels: [bug]
body:
  - type: input
    id: version
    validations: { required: true }
    attributes:
      label: Version
      description: What version is the bug present in?
      placeholder: "v0.1.0 (latest)"
  - type: textarea
    id: description
    validations: { required: true }
    attributes:
      label: Issue Description
      description: |
        Please describe the issue, providing any relevant logs.
